programs:
  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/o1/lz4/o1
    args: ["-f", "-9", "./args/random_text.txt", "./args/random_text.txt.lz4"]
    input: ""

  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/o1/lz4/o1_eng
    args: ["-f", "-9", "./args/random_text.txt", "./args/random_text.txt.lz4"]
    input: ""