programs:
  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/combine/zlib/testprog_default
    args: []
    input: ""

  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/combine/zlib/testprog_energy
    args: []
    input: ""