programs:
  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/cfgsimplify/lz4/default
    args: ["-f", "-9", "./args/random_text.txt", "./args/random_text.txt.lz4"]
    input: ""

  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/cfgsimplify/lz4/energy
    args: ["-f", "-9", "./args/random_text.txt", "./args/random_text.txt.lz4"]
    input: ""