programs:
  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/cfgsimplify/sqlite/default
    args: []
    input: ./args/perf_test.sql

  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/cfgsimplify/sqlite/energy
    args: []
    input: ./args/perf_test.sql