programs:
  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/both/sqlite/o1
    args: []
    input: ./args/perf_test.sql

  - executeable: /home/max/Documents/repos/llvm-energy/examples/optimizations/both/sqlite/o1_eng
    args: []
    input: ./args/perf_test.sql